version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build: ./backend
    ports:
      - "80:80"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
